
export const bookingFields = [
  { name: "guestName", label: 'Имя гостя', type: "text", error: "Введите имя гостя" },
  { name: "guestContact", label: 'Контакт гостя', type: "text", error: "Введите контактную информацию гостя" },
  { name: "checkInDate", label: 'Дата заезда', type: "date", error: "Выберите дату заезда" },
  { name: "checkOutDate", label: 'Дата выезда', type: "date", error: "Выберите дату выезда" },
  { name: "status", label: 'Статус', type: "select", options: ["В ожидании", "Подтверждён", "Отменён"], error: "Выберите статус" },
  { name: "itemId", label: 'ID номера', type: "number" },
  { name: "itemName", label: 'Название номера', type: "text", error: "Введите название номера" },
  { name: "itemType", label: 'Тип номера (Квартира / комната)', type: "text", error: "Введите тип номера" },
  { name: "dailyRate", label: 'Стоимость за день', type: "number", error: "Введите стоимость за день" },
  { name: "address", label: 'Адрес', type: "text", error: "Введите адрес" },
  { name: "houseName", label: 'Название дома', type: "text", error: "Введите название дома" },
  { name: "guestsCount", label: 'Количество гостей', type: "number", error: "Введите количество гостей" },
  { name: "petBreed", label: 'Порода домашнего питомца', type: "text" },
  { name: "petWeight", label: 'Вес питомца', type: "number" },
  { name: "childAge", label: 'Возраст ребенка', type: "number" },
  { name: "smoker", label: 'Курящий', type: "checkbox" },
  { name: "disabledAccess", label: 'Требуется доступ для инвалидов', type: "checkbox" },
  { name: "economyAccommodation", label: 'Экономное размещение', type: "checkbox" },
  { name: "maxServiceAccommodation", label: 'Максимальный сервис', type: "checkbox" },
  { name: "discounts", label: 'Скидки', type: "text" },
  { name: "bonuses", label: 'Бонусы', type: "text" },
  { name: "transfer", label: 'Трансфер', type: "checkbox" },
  { name: "breakfastIncluded", label: 'Завтрак включен', type: "checkbox" },
  { name: "toursIncluded", label: 'Экскурсии включены', type: "checkbox" },
  { name: "workInternet", label: 'Интернет для работы', type: "checkbox" }
];

export const houseFields = [
  { name: "name", label: 'Название дома', type: "text", error: "Введите название дома" },
  { name: "address", label: 'Адрес', type: "text", error: "Введите адрес дома" },
  { name: "description_1", label: 'Описание 1', type: "textarea", error: "Введите Описание 1" },
  { name: "description_2", label: 'Описание 2', type: "textarea", error: "Введите Описание 2" },
  { name: "description_3", label: 'Описание 3', type: "textarea", error: "Введите Описание 3" },
  { name: "description_4", label: 'Описание 4', type: "textarea", error: "Введите Описание 4" },
  { name: "roomCount", label: 'Количество комнат', type: "number", error: "Введите количество комнат" },
  { name: "roomCategories", label: 'Категории комнат', type: "text", error: "Введите категории комнат" },
  { name: "meal", label: 'Питание', type: "text", error: "Введите информацию о питании" },
  { name: "bookingConditions", label: 'Условия бронирования', type: "text", error: "Введите условия бронирования" },
  { name: "checkoutTime", label: 'Время выезда', type: "text", error: "Введите время выезда" },
  { name: "timeToSea", label: 'Время до моря', type: "text", error: "Введите время до моря" },
  { name: "timeToMarket", label: 'Время до магазина', type: "text", error: "Введите время до магазина" },
  { name: "timeToCafe", label: 'Время до кафе', type: "text", error: "Введите время до кафе" },
  { name: "timeToBusStop", label: 'Время до остановки', type: "text", error: "Введите время до остановки" },
  { name: "timeToBusCityCenter", label: 'Время до центра города на автобусе', type: "text", error: "Введите время до центра города на автобусе" },
  { name: "internet", label: 'Интернет', type: "checkbox" },
  { name: "tv", label: 'Телевизор', type: "checkbox" },
  { name: "pool", label: 'Бассейн', type: "checkbox" },
  { name: "babyCot", label: 'Детская кроватка', type: "checkbox" },
  { name: "yard", label: 'Двор', type: "checkbox" },
  { name: "dishwasher", label: 'Посудомоечная машина', type: "checkbox" },
  { name: "washingMachine", label: 'Стиральная машина', type: "checkbox" },
  { name: "diningArea", label: 'Обеденная зона', type: "checkbox" },
  { name: "freeParking", label: 'Бесплатная парковка', type: "checkbox" },
  { name: "roomCleaning", label: 'Уборка номеров', type: "checkbox" },
  { name: "beddingChange", label: 'Смена постели', type: "checkbox" },
  { name: "sharedKitchen", label: 'Общая кухня', type: "checkbox" },
  { name: "iron", label: 'Утюг', type: "checkbox" },
  { name: "bbqGrill", label: 'Мангал для барбекю', type: "checkbox" },
  { name: "refrigerator", label: 'Холодильник', type: "checkbox" },
  { name: "transferService", label: 'Трансфер', type: "checkbox" },
  { name: "laundryService", label: 'Прачечная', type: "checkbox" },
];


export const apartFields = [
  { name: "name", label: 'Название квартиры', type: "text", error: "Введите название квартиры" },
  { name: "address", label: 'Адрес', type: "text", error: "Введите адрес квартиры" },
  { name: "price", label: 'Цена', type: "number", error: "Введите Цену квартиры" },
  { name: "description_1", label: 'Описание 1', type: "textarea", error: "Введите Описание 1" },
  { name: "description_2", label: 'Описание 2', type: "textarea", error: "Введите Описание 2" },
  { name: "description_3", label: 'Описание 3', type: "textarea", error: "Введите Описание 3" },
  { name: "description_4", label: 'Описание 4', type: "textarea", error: "Введите Описание 4" },
  { name: "roomCount", label: 'Количество комнат', type: "number", error: "Введите Количество комнат" },
  { name: "roomCategories", label: 'Категории комнат', type: "text", error: "Введите Категории комнат" },
  { name: "level", label: 'Этаж', type: "number", error: "Введите этаж" },
  { name: "meal", label: 'Питание', type: "text", error: "Введите Питание" },
  { name: "bookingConditions", label: 'Условия бронирования', type: "text", error: "Введите Условия бронирования" },
  { name: "checkoutTime", label: 'Время заселения и выезда', type: "text", error: "Введите время заселения и выезда" },
  { name: "timeToSea", label: 'время до моря', type: "text", error: "Введите время до моря" },
  { name: "timeToMarket", label: 'время до магазина', type: "text", error: "Введите время до магазина" },
  { name: "timeToCafe", label: 'время до кафе', type: "text", error: "Введите время до кафе" },
  { name: "timeToBusStop", label: 'время до автобусной остановки', type: "text", error: "Введите время до автобусной остановки" },
  { name: "timeToBusCityCenter", label: 'время до центра города', type: "text", error: "Введите время до центра города" },
  { name: "internet", label: 'Интернет', type: "checkbox" },
  { name: "tv", label: 'Телевизор', type: "checkbox" },
  { name: "pool", label: 'Бассейн', type: "checkbox" },
  { name: "babyCot", label: 'Детская кроватка', type: "checkbox" },
  { name: "yard", label: 'Двор', type: "checkbox" },
  { name: "dishwasher", label: 'Посудомоечная машина', type: "checkbox" },
  { name: "washingMachine", label: 'Стиральная машина', type: "checkbox" },
  { name: "diningArea", label: 'Обеденная зона', type: "checkbox" },
  { name: "freeParking", label: 'Бесплатная парковка', type: "checkbox" },
  { name: "roomCleaning", label: 'Уборка номеров', type: "checkbox" },
  { name: "beddingChange", label: 'Смена постели', type: "checkbox" },
  { name: "sharedKitchen", label: 'Общая кухня', type: "checkbox" },
  { name: "iron", label: 'Утюг', type: "checkbox" },
  { name: "bbqGrill", label: 'Мангал для барбекю', type: "checkbox" },
  { name: "refrigerator", label: 'Холодильник', type: "checkbox" },
  { name: "transferService", label: 'Трансфер', type: "checkbox" },
  { name: "laundryService", label: 'Прачечная', type: "checkbox" }
]

export const roomFields = [
  { name: "name", label: 'Название комнаты', type: "text", error: "Введите название комнаты" },
  { name: "address", label: 'Адрес', type: "text", error: "Введите адрес дома" },
  { name: "price", label: 'Цена', type: "number", error: "Введите цену номера" },
  { name: "roomCount", label: 'Количество комнат', type: "number", error: "Введите количество комнат" },
  { name: "level", label: 'Этаж', type: "number", error: "Введите этаж" },
  { name: "bedroom", label: 'Спальня', type: "text", error: "Введите Описание Спальни" },
  { name: "bathroom", label: 'Санузел', type: "text", error: "Введите Описание Санузла" },
  { name: "meal", label: 'Питание', type: "text", error: "Введите Питание" },
  { name: "facilities", label: 'Удобства', type: "text", error: "Введите Удобства" }
]

